site_name: EDST8238 Aaron's Placement Portfolio
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep purple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: purple

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

nav:
  - index.md
  - Preparations:
    - 'preparations/timetable.md'
    - 'preparations/paperwork.md'
    - 'preparations/expectations.md'
  - Standards:
    - 'standards/standard1.md'
    - 'standards/standard2.md'
    - 'standards/standard3.md'
    - 'standards/standard4.md'
    - 'standards/standard5.md'
    - 'standards/standard6.md'
    - 'standards/standard7.md'
  - 9COT1:
    - '9COT1/overview.md'
    - '9COT1/lesson-plans.md'
    - '9COT1/lesson1.md'
    - '9COT1/lesson2.md'
    - '9COT1/lesson3.md'
    - '9COT1/lesson4.md'
    - '9COT1/lesson5.md'
    - '9COT1/lesson6.md'
    - '9COT1/lesson7.md'
    - '9COT1/lesson8.md'
    - '9COT1/lesson9.md'
    - '9COT1/lesson10.md'
    - '9COT1/lesson11.md'
    - '9COT1/lesson12.md'
    - '9COT1/lesson13.md'
    - '9COT1/lesson14.md'
    - '9COT1/lesson15.md'
    - '9COT1/lesson16.md'
    - '9COT1/lesson17.md'
    - '9COT1/lesson18.md'
    - '9COT1/lesson19.md'
    - '9COT1/lesson20.md'
    - '9COT1/lesson21.md'
    - '9COT1/lesson22.md'
    - '9COT1/lesson23.md'
    - '9COT1/lesson24.md'
    - '9COT1/lesson25.md'
  - 10IST2:
    - 10IST2/overview.md
  - 10IST5:
    - 10IST5/overview.md
  - 7TEC6:
    - '7TEC6/overview.md'
  - 8TEC6:
    - '8TEC6/overview.md'
  - CT Syllabus:
    - syllabus/stage5/computing-technology/analysing-data/dbms.md
    - syllabus/stage5/computing-technology/software-development/games-simulations-revision.md
  - IST Syllabus:
    - syllabus/stage5/computing-technology/software-development/games-simulations-revision.md

copyright: |
  &copy; 2024 <a href="https://github.com/aaron-beverley-mq" target="_blank" rel="noopener">Aaron Beverley</a>
